cloud:
  aws:
    credentials:
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      access-key: ${AWS_ACCESS_KEY_ID}
    s3:
      bucket: ${AWS_S3_BUCKET}/${profile}
    region:
      static: ap-northeast-2
    stack:
      auto: false